name: Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.5.3

      - name: Using pnpm version 8.6.12
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12

      - name: Using node version 18
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running lint
        run: pnpm run lint
