name: Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-22.04
    env:
      PNPM_VERSION: 8.11.0
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.1.1

      - name: Using pnpm version ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Using node version 20
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running lint
        run: pnpm run lint
