name: Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.2.2

      - name: Using pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Using node version 20
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running lint
        run: pnpm run lint
