name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.2.2
      - name: Installing pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Using latest node version
        uses: actions/setup-node@v4.2.0
        with:
          node-version: latest
          cache: pnpm
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Running lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.2.2
      - name: Installing pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Using latest node version
        uses: actions/setup-node@v4.2.0
        with:
          node-version: latest
          cache: pnpm
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Running typecheck
        run: pnpm typecheck

  typegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.2.2
      - name: Installing pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Using latest node version
        uses: actions/setup-node@v4.2.0
        with:
          node-version: latest
          cache: pnpm
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Running typegen
        run: pnpm typegen
