name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version: [16, 18]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.4.0

      - name: Using pnpm version 7.30.0
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.0

      - name: Using node version ${{ matrix.node_version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running build
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:run
