name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        node_version: [20.18.3, 22.14.0]
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }}
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.2.2

      - name: Installing pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Using node version ${{ matrix.node_version }}
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running typecheck
        run: pnpm typecheck

      - name: Running lint
        run: pnpm lint

      - name: Running tests
        run: pnpm test:run

      - name: Running build
        run: pnpm build

      - name: Running typegen
        run: pnpm typegen
