name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node_version: [18, 20]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.1.5

      - name: Using pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Using node version ${{ matrix.node_version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running build
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:run
