name: Running tests

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running tests
        run: pnpm run test
