name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version: [16, 18, 20]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.5.3

      - name: Using pnpm version 8.6.7
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.7

      - name: Using node version ${{ matrix.node_version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running build
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:run
