name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      PNPM_VERSION: 8.11.0
    strategy:
      fail-fast: false
      matrix:
        node_version: [18, 20]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.1.1

      - name: Using pnpm version ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Using node version ${{ matrix.node_version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running build
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:run
